spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://host.docker.internal:8888"
  cloud:
    config:
        enabled: true
        uri: http://host.docker.internal:8888
        fail-fast: true
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=500, expireAfterWrite=5m