spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user-service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,gateway
